In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [21]:
df = pd.read_csv('/home/danial/Data Science/Credit Risk Analysis/data/feature-engineered/credit_risk_feature_engineered.csv')
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,fe_pay_delta_1_6,fe_utilization_latest,fe_utilization_mean,fe_pay_to_bill_ratio_latest,fe_pay_to_bill_ratio_6,fe_num_delayed_months,fe_max_delay,fe_recent_delay,fe_underpaid_last_month,fe_high_utilization_flag
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.195650,0.064200,0.000000,0.089434,2,2,2,1,0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,-2000.0,0.022350,0.023718,0.000000,0.292791,2,2,-1,1,0
2,3,90000.0,2,2,2,34,0,0,0,0,...,-3482.0,0.324878,0.188246,0.051917,0.108388,0,0,0,1,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,1000.0,0.939800,0.771113,0.042562,0.036259,0,0,0,1,1
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,1321.0,0.172340,0.364463,0.232099,0.540054,0,0,-1,1,0

In [22]:
df = df.drop(columns = ['ID'])

In [23]:
df['EDUCATION'] = df['EDUCATION'].replace({0:4 , 5:4 , 6:4})
df['MARRIAGE'] = df['MARRIAGE'].replace({0:3})

In [24]:
df = pd.get_dummies(df , columns = ['SEX' , 'EDUCATION' , 'MARRIAGE'] , drop_first = True)

In [26]:
target = 'default.payment.next.month'
x = df.drop(columns = [target])
y = df[target]

In [29]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [32]:
X_scaled = pd.DataFrame(X_scaled , columns = x.columns)
final_df = pd.concat([X_scaled , y.reset_index(drop = True)] , axis = 1)
final_df.to_csv('/home/danial/Data Science/Credit Risk Analysis/data/processed/credit_ready.csv')