In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('/home/danial/Data Science/Credit Risk Analysis/data/processed/credit_ready.csv')
df.head()

,Unnamed: 0,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,fe_recent_delay,fe_underpaid_last_month,fe_high_utilization_flag,SEX_2,EDUCATION_2,EDUCATION_3,EDUCATION_4,MARRIAGE_2,MARRIAGE_3,default.payment.next.month
0,0,-1.136720,-1.246020,1.794564,1.782348,-0.696663,-0.666599,-1.530046,-1.486041,-0.642501,...,1.794564,0.524322,-0.601995,0.810161,1.0669,-0.442752,-0.125886,-1.066471,-0.112812,1
1,1,-0.365981,-1.029047,-0.874991,1.782348,0.138865,0.188746,0.234917,1.992316,-0.659219,...,-0.874991,0.524322,-0.601995,0.810161,1.0669,-0.442752,-0.125886,0.937672,-0.112812,1
2,2,-0.597202,-0.161156,0.014861,0.111736,0.138865,0.188746,0.234917,0.253137,-0.298560,...,0.014861,0.524322,-0.601995,0.810161,1.0669,-0.442752,-0.125886,0.937672,-0.112812,0
3,3,-0.905498,0.164303,0.014861,0.111736,0.138865,0.188746,0.234917,0.253137,-0.057491,...,0.014861,0.524322,1.661144,0.810161,1.0669,-0.442752,-0.125886,-1.066471,-0.112812,0
4,4,-0.905498,2.334029,-0.874991,0.111736,-0.696663,0.188746,0.234917,0.253137,-0.578618,...,-0.874991,0.524322,-0.601995,-1.234323,1.0669,-0.442752,-0.125886,-1.066471,-0.112812,0

In [9]:
X = df.drop('default.payment.next.month' , axis = 1)
y = df['default.payment.next.month']

X_train , X_temp , y_train , y_temp = train_test_split(X , y , test_size = 0.2 , stratify = y , random_state = 7)

In [11]:
X_val , X_test , y_val , y_test = train_test_split(X_temp , y_temp , test_size = 0.5 , stratify = y_temp , random_state = 7 )

In [13]:
print("Train set class distribution:\n", y_train.value_counts(normalize=True))
print("\nValidation set class distribution:\n", y_val.value_counts(normalize=True))
print("\nTest set class distribution:\n", y_test.value_counts(normalize=True))

Train set class distribution:
 default.payment.next.month
0    0.778792
1    0.221208
Name: proportion, dtype: float64

Validation set class distribution:
 default.payment.next.month
0    0.779
1    0.221
Name: proportion, dtype: float64

Test set class distribution:
 default.payment.next.month
0    0.778667
1    0.221333
Name: proportion, dtype: float64

In [14]:
train_df = pd.concat([X_train, y_train], axis=1)
val_df = pd.concat([X_val, y_val], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)


print("Train size:", train_df.shape)
print("Validation size:", val_df.shape)
print("Test size:", test_df.shape)

Train size: (24000, 49)
Validation size: (3000, 49)
Test size: (3000, 49)

In [15]:
train_df.to_csv('/home/danial/Data Science/Credit Risk Analysis/data/processed/Final/train.csv', index=False)
val_df.to_csv('/home/danial/Data Science/Credit Risk Analysis/data/processed/Final/val.csv', index=False)
test_df.to_csv('/home/danial/Data Science/Credit Risk Analysis/data/processed/Final/test.csv', index=False)